mybatis:
  mapper-locations: classpath:mapping/*.xml
server:
  port : 8090
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    name: miaosha
    url: jdbc:mysql://miaosha.ctqjuwexc9tq.us-east-1.rds.amazonaws.com:3306/miaosha
    username: root
    password: rootroot